### ISSUE TITLE
Certain show crashing the app

### ISSUE THREAD

**Issue by X712** [PopcornTimeTV/PopcornTimeTV#385] opened 2017-03-04 12:49 UTC
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using install script (`swift install.swift`), make sure the latest release is selected (the further up the list, the later). If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`).
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.

#### Expected Behaviour

Go into the selected show, in this case Real Time with Bill Maher
#### Actual Behaviour

The app crashes instantly when selected the previously mentioned show. For some reason it doesn't happen with other shows like TWD or The 100

#### Steps to reproduce the behaviour

1. Go the Shows Tab
2. Select Real Time with Bill Maher
3. App crashes

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-03-04 17:24
This is an [issue with the API](https://github.com/popcorn-official/popcorn-api/issues/73). We made them aware of the issue a few months ago but there still appears to be no progress. I have fixed the crash in the latest commit but the show will still not load until the issue is fixed on the API end.

**Closed by FlaviaBondJamesBondsHusband** 2017-03-04 17:24 UTC

**Comment by joostiphone** [comment] 2017-03-05 09:58
Can you please issue the latest version to the Cydia repo?
