### ISSUE TITLE
Subtitle Sync

### ISSUE THREAD

**Issue by damiantrimboli** [PopcornTimeTV/PopcornTimeTV#286] opened 2017-01-02 05:15 UTC
I think that the subtitle synchronization in tvOS and iOS is not working ok. 
Tested multiple movies and languages, sometimes the subtitles are ahead the video and sometimes behind. Tried using the offset options but couldn't make it work either.
The same movies and languages in the Mac versions of PopcornTime are working ok.
Also, the same movies and subtitles files in Plex or Squire (in tvOS)  are synced.
Is there anything i'm doing wrong?

**Comment by hvluu** [comment] 2017-01-02 23:11
i dont have the offset option anymore in the latest release. the file was removed but I confirmed that the subtitle sync in the latest release isn't working correctly.

**Comment by Evhelden** [comment] 2017-01-03 15:57
Confirm. Subtitles in 3.0 not in sync for Dutch language for movies on 1080p.
Changing the subtitles sync does not stick. Selecting + or - does select, but no change. When going back to the menu, stays on 0. 
Hope this can be fixed.

**Comment by r1qu3br** [comment] 2017-01-04 01:57
I have this problem too at 3.1

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-01-05 18:58
Issue fixed in master

**Closed by FlaviaBondJamesBondsHusband** 2017-01-05 18:58 UTC

**Comment by Evhelden** [comment] 2017-01-06 09:54
Pulled the master. Dutch subtitles (only one tested) not yet in sync. Better, but still off with the spoken language. (Tested only Marco Polo season 2 episode 1).

**Comment by gustavolessadublin** [comment] 2017-01-06 17:12
I confirm the same issue. I just finished updating all files and it persists.
Portuguese (BR) and English for The Accountant movie.

**Comment by r1qu3br** [comment] 2017-01-06 17:28
@gustavolessadublin Are you sure? I am also Brazilian and I tested with subtitles in English and Portuguese (BR) and had no problem, I just had to download the files manually because by the terminal it comes the 3.1.0 version yet

**Comment by gustavolessadublin** [comment] 2017-01-06 17:53
@r1qu3br Well, I updated via install.swift. I thought it would download the latest files automatically.
I think, then, I might be still using the previous version.

**Comment by damiantrimboli** [comment] 2017-01-10 02:50
@FlaviaBondJamesBondsHusband this issue is still not fixed. Can we re open it?. The commit you referenced is about fixing the delay selection (i'm going to test it now). But still subtitles load out of sync. Subtitles that I checked in other platforms and works very well.
In those other platforms I rarely use the offset option because the subtitles are already polished. In this version of PopCornTime i could not find any subtitle working ok. :(

**Comment by gustavolessadublin** [comment] 2017-01-10 13:34
I second what @damiantrimboli pointed out. 
I have to set delay almost every time. 
For example, while watching Snowden I couldn't set the correct delay, since it was more than +5.0.

**Comment by Evhelden** [comment] 2017-01-12 16:10
I hope this can be re-opened as well. Also i do not get the subtitle delay from the pull down menu working.

**Comment by damiantrimboli** [comment] 2017-01-21 13:26
@FlaviaBondJamesBondsHusband is this issue going to be reopened again since it is not fixed? If it continues closed it will remain out of sight.

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-01-21 13:49
Subtitle sync issue is fixed. If the subtitles are out of sync, use the sync feature. We do not create subtitles so it is not our problem if they are out of sync. The subtitles are out of sync because they are supposed to be for legit versions, ie. the ones that you pay for, not the torrented versions which may have a different duration to the legit versions due to the person who uploads them. This issue will not be re-opened as it is not an issue. If you have a problem with the subtitle syncing, post an issue in the [OpenSubtitles Forum](https://forum.opensubtitles.org/). We can do nothing about this

**Comment by damiantrimboli** [comment] 2017-01-21 15:18
@FlaviaBondJamesBondsHusband It seems that you didn't read the hole thread. I'm posting this as an issue since the same movie with the same subtitles are working ok in the Mac version of PopcornTime. This problem is exclusively from tvOS and iOS versions and it seems to be new. Can you check at least the movies that i'm telling you as an example that you can't even sync them with the offset feature? "Snowden", "Inferno", for example. Check them in the iOS/tvOS version (15 seconds of offset) and then check the PC/Mac version, totally synced. So, there is a problem with this version. There is just one movie that I could find that works synced without needing to set the offset, the other ones are just out of sync. Please, at least try it. I don't want to bother you but this is making PopcornTime totally useless for me and a lot of people more.

**Comment by Evhelden** [comment] 2017-01-22 06:36
Flaviabondjamesbondhusband,

Can not get the sync feature to use. Can you help? The pull down menu is fine, but the selected + or - 5s does not stick. Pulling down again the sync remains on 0.0 s. What am I doing wrong?

Tx

**Comment by ceuaugusto** [comment] 2017-01-25 16:06
I have the same problem: selecting a + or - setting on subtitle delay menu and it does not stick. I use the tvOS version 3.0.0 installed by install.swift file.

**Comment by ceuaugusto** [comment] 2017-01-30 20:53
@FlaviaBondJamesBondsHusband please, see this topic again!

**Comment by maiiikell1995** [comment] 2017-03-05 19:11
Im on the latest version 3.1 got the zip form github updated via the podfile and still cant get it to work even with die sub delay option. 
does some have a solution already?

**Comment by dyorgio** [comment] 2017-03-31 19:37
Same problem here too. sub delay option don't works.
