### ISSUE TITLE
Crashing swiping down for subs on TvOs 11.4

### ISSUE THREAD

**Issue by diegosm3** [PopcornTimeTV/PopcornTimeTV#668] opened 2018-06-02 14:55 UTC
App version: 19
iOS/tvOS version: 11.4

I got an issue when I tried to acess the menu (subs,info,audio), my app crash and I cant change or active any subs, so cant use the app. 

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ X] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [X ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by maitremiju** [comment] 2018-06-02 18:06
Same here!

**Comment by malten82** [comment] 2018-06-02 19:39
I Have just installed popcorn time on my Apple TV 4 and it worked great with subs
The day after my Apple TV updated to the new version and like the above describes ’true to change sub the app crash’
Something about the new iOS.......

**Comment by xandervr** [comment] 2018-06-03 17:46
The problem lies within the speaker selection when swiping down. tvOS 11.4 enables Airplay 2 functionality, the speaker selection in the Popcorn Time app is still using Airplay 1 which causes an error that leads into a crash of the app. I was able to fix the issue by disabling the speaker selection... The full fix is to integrate Airplay 2 into the Popcorn Time app...

**Comment by diegosm3** [comment] 2018-06-03 20:09
I didnt figure out how to disable the speaker selection. Can you teach me?

**Comment by xandervr** [comment] 2018-06-03 20:11
@diegosm3 I fixed the problem, I will create a pull request.

**Comment by xandervr** [comment] 2018-06-03 20:30
@diegosm3 look at my fork https://github.com/xandervr/PopcornTimeTV, you can download the fixed source over there while we wait for the pull request to come through.

**Comment by diegosm3** [comment] 2018-06-03 21:00
@xandervr I read your post but I don't know how to install the application from this way, can you teach me?

**Comment by diegosm3** [comment] 2018-06-03 21:05
I cant build the application, my SO is windows.

**Comment by xandervr** [comment] 2018-06-04 07:35
@diegosm3 Windows will be unable to build this... You need a Mac for that

**Comment by nuvzzy** [comment] 2018-06-04 12:08
by disabling the speaker section, but having the Apple TV 4 speakers set to stereo homepods in settings not app does it still have the lag?

**Comment by xandervr** [comment] 2018-06-04 13:42
I don’t know, I don’t have the HomePod speaker.

**Comment by engom1987** [comment] 2018-06-04 16:48
please can you give us the .IPA , because i got so many errors when i try to complie the project :)

**Comment by xandervr** [comment] 2018-06-04 17:36
I will in a couple of hours, busy watching WWDC atm

**Comment by engom1987** [comment] 2018-06-04 21:56
@xandervr many thanks :)

**Comment by diegosm3** [comment] 2018-06-04 22:36
@xandervr Thanks i will be waiting for this. Hugs

**Comment by engom1987** [comment] 2018-06-05 19:06
@xandervr i get the following errors while compiling 

diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by xandervr** [comment] 2018-06-05 19:18
You need to install cocoapods

**Comment by xandervr** [comment] 2018-06-05 19:36
> brew install cocoapods
Go to the dir of the PopcornTime project
> pod install

**Comment by engom1987** [comment] 2018-06-06 02:04
@xandervr Many thanks that did the trick , and here we go no more crashes :)

**Comment by xandervr** [comment] 2018-06-06 12:01
Unsigned IPA: https://mega.nz/#!fPA31CRL!sEk8465A48sqFIVB8XLLYNpJwYAxe-1FA0Ir-GnDV64

**Comment by diegosm3** [comment] 2018-06-06 12:50
@xandervr Thanks a lot, Im gonna test and I'll give the feedback ASAP.

**Comment by diegosm3** [comment] 2018-06-06 13:29
@xandervr Its working, for now. Many thanks buddy.

**Comment by galooper** [comment] 2018-06-07 16:10
It’s working but in all movies there's no subtitles to choose. There’s another fix for that?? Thanks for your support

**Comment by pbl4845** [comment] 2018-06-07 16:21
@galooper close the app and relaunch it again(at least works for me when there are no subtitles available). This is something that happens from time to time, same as random sudden close of the app.
@xandervr thanks! I also confirm the issue is solved with your IPA

**Comment by Tom2527** [comment] 2018-06-07 20:37
It's working again. Nice! 
When subtitles are missing, you need to kill the app (not only close it) and restart it

**Comment by angryDuck2** [comment] 2018-06-09 11:17
Thank you @xandervr for the work you made. We will be incorporating this change on the ipa distributed from this repo on the next version along with other changes

**Closed by angryDuck2** 2018-06-09 11:17 UTC
