### ISSUE TITLE
Stream stops midway

### ISSUE THREAD

**Issue by pnewell** [PopcornTimeTV/PopcornTimeTV#97] opened 2016-05-15 19:39 UTC
Have an issue where streams stop randomly midway. Not sure why it is happening. Also, if I start a stream, and fast forward it never resumes.

**Comment by buzzel** [comment] 2016-05-16 00:13
@pnewell Run a `pod update` and see if it updates anything. This should of been fixed with the 0.6.0 release but Im wondering if some people haven't properly updated their pods.

**Comment by pnewell** [comment] 2016-05-16 00:51
@buzzel I just got my apple tv/installed 0.6.2 today for the first time

**Comment by pnewell** [comment] 2016-05-16 16:58
What is a pod update?

**Comment by pbo1976** [comment] 2016-05-16 21:15
Movies also stop streaming within the first 5 minutes or so. Tv shows stream mostly fine for me.

**Comment by pnewell** [comment] 2016-05-16 21:24
This is happening to tv shows for me

**Comment by RefusedFlow** [comment] 2016-05-21 11:55
Closing this issue as a duplicate of #96

**Closed by RefusedFlow** 2016-05-21 11:55 UTC
