### ISSUE TITLE
Errors With AEXML

### ISSUE THREAD

**Issue by moh0sw** [PopcornTimeTV/PopcornTimeTV#75] opened 2016-09-13 00:12 UTC
Just tried to run popcorn time on my Apple TV4 with the Xcode and got these errors

Version 1.0.5 ( 59 commit )

Xcode ( 7.3.1 ) macOS ( 10.12 (16A320) GM )

<img width="253" alt="screen shot 2016-09-13 at 3 06 24 am" src="https://cloud.githubusercontent.com/assets/19555995/18457253/d554f83a-795f-11e6-9625-ae802c12233b.png">
<img width="253" alt="screen shot 2016-09-13 at 3 06 33 am" src="https://cloud.githubusercontent.com/assets/19555995/18457254/d5557ada-795f-11e6-9fbf-50a88a99de66.png">

**Comment by galdo320** [comment] 2016-09-13 02:58
same here. . .

**Comment by wahlmanj** [comment] 2016-09-13 05:06
You must build from scratch everytime. Follow this exactly again to compile:

https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/README.md

**Comment by moh0sw** [comment] 2016-09-13 05:09
@wahlmanj yeah that what I do every time even i delete the DerivedData and every thing!
Used ( swift install.swift ) and ( pod install ) and ( pod update )

**Comment by wahlmanj** [comment] 2016-09-13 05:11
Worked fine here...

**Comment by rafaelfsramos** [comment] 2016-09-13 07:46
Same problem.

**Comment by malhaar** [comment] 2016-09-13 13:14
same problem

**Comment by moh0sw** [comment] 2016-09-13 14:14
@popcornMaster @tvOSPopcorn @FlaviaBondJamesBondsHusband @Hackormahn Any Thing?

**Comment by FlaviaBondJamesBondsHusband** [comment] 2016-09-13 17:15
This is an issue with AEXML and the fact that our project doesnt support swift 3 yet. Fix is on the way

**Comment by galdo320** [comment] 2016-09-13 20:56
@FlaviaBondJamesBondsHusband  I tried it but It doesn't work

**Comment by GerTeunis** [comment] 2016-09-13 20:59
The pod AlamofireXMLRPC depends on the latest AEXML which just updated with swift 3 support. Until somebody clones AlamofireXMLRPC with specific AEXML pre swift 3 and updates the podfile of popcorn it will not work anymore

**Comment by moh0sw** [comment] 2016-09-14 03:26
@FlaviaBondJamesBondsHusband just tried ( pod repo update; pod update; ) and the same problem
:(

**Comment by rafaelfsramos** [comment] 2016-09-14 03:44
@FlaviaBondJamesBondsHusband what do you need? the ipa file to reinstall?

**Comment by wahlmanj** [comment] 2016-09-14 04:42
Could you upload the latest for us? 

https://github.com/PopcornTimeTV/PopcornTimeTV/issues/62

**Comment by gustavgesar** [comment] 2016-09-14 14:30
Is there a fix for this issue? Would downloading Xcode 8 resolve it?

**Comment by BilalBaydoun** [comment] 2016-09-15 10:38
can anyone please put the IPA file and I will resign it till the issue is fixed?

Thank you

**Comment by moh0sw** [comment] 2016-09-15 13:13
3 days without any fix
wow

**Comment by moh0sw** [comment] 2016-09-15 13:25
And now the same problem with ObjectMapper (226 Errors)

**Comment by rafaelfsramos** [comment] 2016-09-15 16:46
https://www.dropbox.com/sh/dh1k3r2ul98nbqu/AACDuZyFP_TSBs0wdJ-yhYqya?dl=0
This link will be deleted today

**Comment by moh0sw** [comment] 2016-09-15 17:05
@rafaelfsramos yeah it's 1.0.3.1 (46)

GUYS WE NEED A FIX OR A 1.0.5 IPA

**Comment by Yonikenneth** [comment] 2016-09-15 18:34
Hi @rafaelfsramos how would I install this resigned .ipa file on my Apple TV? I'm too experiencing the AEXML issues (at least is seems so):

I'd love to hear from you/help you out.

`install.swift:115:4: error: missing argument label 'args:' in call`

**Comment by Mossito** [comment] 2016-09-15 18:58
Thanks for the IPA, im having the same problem with the pods,I  tried to fix it for hours but its a nightmare for me... I will keep looking at it.

@Yonikenneth you have to resign the ipa with your profile with the app iOS-app-signer, then install from Xcode - window -devices.

I love this project, its normal that these problems happen during these upgrade days. Thank you very much for your hard work to the developers. I really appreciate it.

**Comment by moh0sw** [comment] 2016-09-16 00:23
Guys do u think updating to xcode 8.0 will solve the problem?

**Comment by moh0sw** [comment] 2016-09-16 20:53
xcode 8.0 isn't supported with 1.0.5 (62) version at all

**Comment by Hackormahn** [comment] 2016-09-16 22:25
For now, until we update everything to Swift 3, manually resign the iPA on our releases page and install it that way.

**Closed** 2016-09-25 16:06 UTC
Labels: wontfix
