### ISSUE TITLE
9th minute break...

### ISSUE THREAD

**Issue by tomto147** [PopcornTimeTV/PopcornTimeTV#96] opened 2016-05-15 18:03 UTC
After upgrading to 0.6.2 I am experiencing an issue with every single movie I am trying to play. Everything is ok until ca. 9min including subtitles and everything. Then the mowie stops and AppleTV quits the app completly. Anyone experiencing something similar? It happens always aroun 9th minute of playback.

**Comment by buzzel** [comment] 2016-05-15 18:23
@tomto147 This is news to us so we'll look into this.

**Comment by buzzel** [comment] 2016-05-15 18:38
@tomto147 Run a pod update and then test again. Not having any issues with this.

**Comment by tomto147** [comment] 2016-05-17 13:22
@buzzel I have installed a clear new app and thought it was working properly until my AppleTV updated automatically to 9.2.1 and now same problems are back (although I have installed the app once more). At least 4 films stoped around 9th minute and the app quit to the home screen. But one film played properly till the end. So... still no idea where is the problem...

**Comment by tomto147** [comment] 2016-05-17 19:08
OK now I can confirm this 9th minute break is random. Happens from time to time on different movie, and again same movie a day later plays OK... so not possible to trace the problem...

**Comment by pbo1976** [comment] 2016-05-17 20:39
I experience same 9th minute app quit on a movie.

**Comment by RefusedFlow** [comment] 2016-05-17 21:50
@pbo1976 @tomto147 Hmm unable to reproduce this myself, have you tried pulling from the master branch? 😄

**Comment by tomto147** [comment] 2016-05-18 11:07
@RefusedFlow 
I am always pulling from the master branch (not updating only the changes)...

**Comment by pbo1976** [comment] 2016-05-18 13:48
Ok. All good since 0.6.3

**Comment by tomto147** [comment] 2016-05-18 19:17
@pbo1976 
Sadly not for me. I am still gating random quits around 9th minute even with 0.6.3. Playing the same movie again is most of the time successful.

**Comment by drew5494** [comment] 2016-05-19 22:39
Ya just noticed this issue.  
 I think its because I updated twos but then again I usually just watch TV shows.

**Comment by pbo1976** [comment] 2016-05-20 20:35
It just happened to me again., not sure at what exact minute, but it was definitely at the beginning ca.20-30

**Comment by RefusedFlow** [comment] 2016-05-21 11:53
I myself have had this issue once, i'll try and reproduce this issue and see what error xCode throws out.

**Comment by T0XicGreif3r** [comment] 2016-05-23 11:19
Any status update on reproduction? I get it on every movie I watch but it's around 13 minutes on 2001: A Space Oddessy.

**Comment by buzzel** [comment] 2016-05-26 18:11
Does the app crash, or does it just stop streaming?

**Comment by drew5494** [comment] 2016-05-26 18:25
It stops streaming no craah

**Comment by T0XicGreif3r** [comment] 2016-05-26 18:58
I got a crash. Sometimes it just stops streaming. You also can't pause for long, fast forward or rewind or it will not play.

**Comment by buzzel** [comment] 2016-05-26 23:17
I've moved this to the PopcornTorrent repo so I'll dig into this sometime later this week. For now, i'm closing it here though.

**Closed by buzzel** 2016-05-26 23:17 UTC
Labels: sev:high, type:bug
