### ISSUE TITLE
Duplicated entries on Trakt.tv

### ISSUE THREAD

**Issue by victorvernili** [PopcornTimeTV/PopcornTimeTV#470] opened 2017-05-12 01:01 UTC
App version: 3.1
iOS/tvOS version: Apple TV 4, tvOS 10.2

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

After watching 1 full episode or at least half of it, track it **once** to trakt.tv.
After watching less than half of an episode, not track it.

#### Actual Behaviour

It is submiting multiple entries to the watch history on every episode:

![image](https://cloud.githubusercontent.com/assets/28638886/25977901/3fdadcea-3695-11e7-9334-e32995320119.png)

#### Steps to reproduce the behaviour

1. Watch an episode
2. [Do normal stuff -- go back some times, minimize the app sometimes, ...]
3. Finish watching the episoe
4. Check trakt.tv -- there are multiple instances, all pointing to the same timestamp

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-05-19 18:35
Needs further investigation. Any help would be appreciated as we don't have a lot of time at the moment.

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-07-21 01:21
We are unable to reproduce this issue and will therefore be closing as no help was recieved

**Closed by FlaviaBondJamesBondsHusband** 2017-07-21 01:21 UTC
Labels: bug, help wanted
