### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by matiasloda** [PopcornTimeTV/PopcornTimeTV#60] opened 2016-04-21 22:01 UTC
I want to ask to anyone if we can add an option to watch movies with subtitles as the desktop app.

**Comment by Breaking1** [comment] 2016-04-21 22:41
As you can see here this has already been requested #11

**Comment by matiasloda** [comment] 2016-04-21 23:15
ok sorry.

**Comment by buzzel** [comment] 2016-04-22 17:52
Closing this as it's a duplicate of #11

**Closed by buzzel** 2016-04-22 17:52 UTC
