### ISSUE TITLE
Italian subtitles

### ISSUE THREAD

**Issue by bubez81** [PopcornTimeTV/PopcornTimeTV#66] opened 2016-09-10 07:26 UTC
Hi! Great app!! Unfortunately there are never Italian subtitles and it's strange because on opensubtitles I can always find the right Italian subtitle

**Comment by Beorn1988** [comment] 2016-09-10 11:36
I commented on this a while ago. When it comes to swedish subs I can find them there aswell. For the djungle book for example. But my guess is that they aren't hashed for that particular torrent which is used as a movie. But I'm hoping for a download option to be implemented later on. Then even if a sub dont fit exactly you can just adjust sub with delays.

**Comment by popcornMaster** [comment] 2016-09-10 20:16
As it is already said, duplicate of #35 . Closing!

**Closed by popcornMaster** 2016-09-10 20:16 UTC
