### ISSUE TITLE
Unable to play pre-downloaded episode

### ISSUE THREAD

**Issue by sweetw0r** [PopcornTimeTV/PopcornTimeTV#484] opened 2017-06-04 03:38 UTC
App version: 3.1.2
tvOS version: 10.2.1

Make sure these boxes are checked before submitting your issue - thanks!

- [x] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [x] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [x] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Pre-downloaded episode should play
#### Actual Behaviour

It is continuously loading

#### Steps to reproduce the behaviour

1. In Apple TV app open an episode and pause it
2. When it's download play it
3. Repeat 2 after killing the app

http://g.recordit.co/VcW7iSm0ws.gif

[the_americans.txt](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1050099/the_americans.txt)

**Comment by sweetw0r** [comment] 2017-06-05 03:28
Same problem is happening when user tries to replay last 30 seconds or scroll back to some previous moments

**Comment by sweetw0r** [comment] 2017-06-06 05:34
The only way to get out and make it playable is to clear the cache and re-download the whole thing again. Then cross fingers so it won't happen again

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-06-10 16:09
Are you still having this issue? We fixed some bugs r.e. streaming in the latest master commit. Do you wanna check them out?

**Comment by SerhiiAksiutin** [comment] 2017-06-11 04:09
Currently I am having trouble to build it
<img width="678" alt="screen shot 2017-06-10 at 9 11 16 pm" src="https://user-images.githubusercontent.com/27512156/27008229-157577dc-4e21-11e7-82a5-ffb6c20947da.png">

**Comment by sweetw0r** [comment] 2017-06-11 04:11
I am having trouble to build it:
<img width="678" alt="screen shot 2017-06-10 at 9 11 16 pm" src="https://user-images.githubusercontent.com/12688470/27008237-4d038b30-4e21-11e7-9b21-b4d26c3dd0f6.png">

CC: @FlaviaBondJamesBondsHusband

**Comment by sweetw0r** [comment] 2017-06-11 06:04
That's all I got with the current build. 
<img width="964" alt="screen shot 2017-06-10 at 11 05 06 pm" src="https://user-images.githubusercontent.com/12688470/27008777-f3ea981c-4e30-11e7-81af-ab0ad7274997.png">
Thoughts?

Note: iOS version has been built successfully

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-06-11 11:33
Quoting from the commit message:

> THIS IS FOR IOS ONLY. TVOS WILL NOT COMPILE.

**Comment by SerhiiAksiutin** [comment] 2017-06-11 18:36
The issue is about tvOS.

**Comment by sweetw0r** [comment] 2017-06-11 18:39
The issue is about tvOS app

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-06-11 20:43
They have the exact same code base so any issue that exists on tvOS exists on iOS too

**Comment by sweetw0r** [comment] 2017-06-12 03:58
OK. I'll verify the issue when tvOS build arrived.

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-06-12 13:47
@sweetw0r I don't think you understand. They have the exact same code base so any issue that exists on tvOS exists on iOS too. This means that whatever issue you were having with episodes not playing on tvOS, that issue would have existed on iOS too. So, even though the tvOS build is not compiling, the iOS build is, so if you test with the iOS build and the issue is fixed, it would be fixed on tvOS too

**Comment by sweetw0r** [comment] 2017-06-12 17:14
Yeah. You're right. I had no idea that behavior on both platforms that similar. I just don't really utilize the app on iPhone/iPad obviously because of the screen size. But I did check the iOS build and experience regarding the issue feels way better. 

No need to clean cache to get playback working. Now It's getting stuck only if speed is extremely slow (3-4 seeds). Repeating last 30 seconds is also fine. 

Can't wait to double-check it on Apple TV

**Closed** 2017-06-13 12:48 UTC
Labels: resolved
