### ISSUE TITLE
Torrent Health 

### ISSUE THREAD

**Issue by moh0sw1** [PopcornTimeTV/PopcornTimeTV#349] opened 2017-02-13 20:55 UTC
it will be nice to make this future available for tvOS like the desktop version
so it shows you the torrent health if its excellent (green) good (light green) medium (yellow) bad (red)

I hope you understand what I meant

Thanks!

**Comment by FlaviaBondJamesBondsHusband** [comment] 2017-02-14 16:41
This used be a feature in the application but because the seeds and peers from the API is so far from correct, the torrent health displayed had 0 actual relevance to the torrents actual health. We can look into it once the issue is fixed with the API

**Closed by FlaviaBondJamesBondsHusband** 2017-02-14 16:41 UTC
