### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by QiuIcs** [PopcornTimeTV/PopcornTimeTV#568] opened 2018-03-02 20:12 UTC
App version: 3.2.8
iOS version: 9.3.5 (iPad 3 Wifi)

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour

Play video

#### Actual Behaviour

Crashes every time upon starting the video

#### Steps to reproduce the behaviour

Play any video

**Comment by popcornMaster** [comment] 2018-03-02 22:08
For now please only stream 720p videos, as VLCKit is crashing on 1080p video!

**Comment by majedsahi** [comment] 2018-03-02 22:32
Same issue here. Movies take ages to load then crash upon playing on 3.2.8 on TVOS. 
Tried the “lowest quality” option which worked but then crashed after playing the movie for a few minutes.

**Comment by rajanrengasamy** [comment] 2018-03-03 02:26
Same issue here with 3.2.8 TV shows and movies simply crash
tried all qualities, tried clearing cache, tried re-installing. 
Same issue.

**Comment by thekennygreene** [comment] 2018-03-03 03:32
Same issues as above. Tried playing Justice League and it keeps crashing app, this video used to work on the previous version. Crashes on both 720p and 1080p.

**Comment by damianxd** [comment] 2018-03-03 19:08
It’s the same for me, the app crashes even on 720p just at the beginning

**Comment by ctschalk** [comment] 2018-03-04 00:36
Same for me crashing all the time.

**Comment by thekennygreene** [comment] 2018-03-04 02:23
A somewhat of a fix I have found on the Apple TV 4 for when it crashes the app on movie loading, is to go into the the Apple TV settings and restart the Apple TV, then try and load the movie again once it restarts. Seems to work most times.

**Comment by rajanrengasamy** [comment] 2018-03-04 03:49
thanks mate, I just downgraded to 3.2.6 and enjoying those bugs instead

**Comment by bao3** [comment] 2018-03-04 15:34
Crash on tvOS 10.2.2 and iOS 11.1.2 . Everytime  I watch video on 720P or I downloaded 720P video and click watch . PopcornTime version 3.2.8 , Subtitle :ChineseSimple

**Comment by popcornMaster** [comment] 2018-03-06 22:53
New release 3.2.9 should be relieved of this issue!

**Comment by ctschalk** [comment] 2018-03-07 00:20
I tested 3.2.9 out and so far its crashed twice.. once in 1080p after a few minutes and once in 720p

**Comment by angryDuck2** [comment] 2018-03-07 00:59
Please pull your crash report using this (guide)[https://gist.github.com/jmoody/f75daf5eab821eb40e79] and post it here

**Comment by lawbokent** [comment] 2018-03-07 16:17
hi, just tried to play some tv series with 3.2.9, it crashed after a few minutes (was in 720p)
log attached for your reference
thanks for looking into it
[PopcornTime  7-3-2018, 23-40.crash.zip](https://github.com/PopcornTimeTV/PopcornTimeTV/files/1789893/PopcornTime.7-3-2018.23-40.crash.zip)

**Comment by angryDuck2** [comment] 2018-03-07 22:00
Can anyone confirm for me if closing all open apps before streaming or downloading a movie makes the app work without crashing?

**Comment by QiuIcs** [comment] 2018-03-07 22:20
This seems to fix the crash.

**Comment by popcornMaster** [comment] 2018-03-09 10:31
Can someone run a `pod update` on the terminal and then run the application on his device again, I think we have found a permanent fix

**Comment by rajanrengasamy** [comment] 2018-03-10 04:03
Updated to 3.2.9. 
Closed all apps
Restarted Apple TV 

Works amazingly

**Comment by angryDuck2** [comment] 2018-03-10 09:27
@rajanrengasamy did you build from the source code or just installed the ipa? Please try to follow our build from source guide as we should have a solution that does not require closing apps

**Comment by popcornMaster** [comment] 2018-03-11 13:36
I am going to repeat can anyone that builds this app from source code do a `pod update` and try 3.2.9 again. We believe that we found the solution to this crash but we need further testing! Help out!

**Comment by damianxd** [comment] 2018-03-11 15:27
I tried to build it and install it from source but I couldn't make it run on my Apple TV. It failed at installing, but I could build it. I don't know what the problem was.

**Comment by angryDuck2** [comment] 2018-03-11 17:24
@damianxd Could you post the installation error?

**Comment by damianxd** [comment] 2018-03-11 18:11
nevermind, I just had to remove the version previously installed. It’s working fine for me so far, no crash yet

**Comment by Midifreakz** [comment] 2018-03-11 18:14
Did not have the time to try to compile one myself but on the .9 official release it just won't work, Crashes on the second playback time and then won't play anything even after closing and restarting... I keep using .6 for now.

**Comment by fredimesper** [comment] 2018-03-12 01:18
Im having the same issue, the app seems to crash every time the cache memory hits 1.82 gb, i dont know if this is relevant, but maybe the app is filling up the ram memory on the apple tv?

**Comment by damianxd** [comment] 2018-03-12 11:00
I just got a crash with the built version. It happend after pausing a video and then closing the app, the second time I tried to watch the same movie, it just crash until I cleared the cache. I think it is a problem while reading the previous video information, a corrupted one makes the app crash. Maybe you could just delete the stored cache for that movie instead.

**Comment by damianxd** [comment] 2018-03-12 11:02
with Starwars: The last Jedi, It does the same problem if I just get to the title scroll and then stop the video and watch it again. The app will just crash everytime

**Comment by angryDuck2** [comment] 2018-03-12 11:09
@damianxd Thanks for the thorough testing. Could you get the crash log from the device, guide post a few posts above, and also tell me if the movie was done downloading when you paused it?

**Comment by damianxd** [comment] 2018-03-12 11:34
@angryDuck2 here it is:
`{
  "crashReporterKey" : "ac04f558dd8014809888626463b0dfcda0a8cf8b",
  "kernel" : "Darwin Kernel Version 17.4.0: Wed Dec 13 08:39:13 PST 2017; root:xnu-4570.40.9~5\/RELEASE_ARM64_T7000",
  "product" : "AppleTV5,3",
  "incident" : "253F129A-2EBB-4F30-9058-E10642D6E2F6",
  "date" : "2018-03-12 08:31:41.29 -0300",
  "build" : "Apple TVOS 11.2.6 (15K600)",
  "timeDelta" : 92,
  "memoryStatus" : {
  "compressorSize" : 72764,
  "compressions" : 113014,
  "decompressions" : 2541,
  "zoneMapCap" : 402653184,
  "largestZone" : "APFS_4K_OBJS",
  "largestZoneSize" : 13107200,
  "pageSize" : 16384,
  "uncompressed" : 95907,
  "zoneMapSize" : 62029824,
  "memoryPages" : {
    "active" : 23021,
    "throttled" : 0,
`

The movie was not done loading yet and on one sit, without pausing, the movie plays just right. 
I can reproduce the problem every time I stop the movie and then resume it again.

**Comment by angryDuck2** [comment] 2018-03-12 11:36
I will need the entire crash file if this is possible, it is a really small file to upload. Again, here is the (guide)[https://gist.github.com/jmoody/f75daf5eab821eb40e79]

**Comment by damianxd** [comment] 2018-03-12 11:39
Yeah, that's all I got from it, even after exporting.

**Comment by angryDuck2** [comment] 2018-03-12 15:52
Issue identified and will be resolved in a future release. Thanks for reporting

**Closed by angryDuck2** 2018-03-12 15:52 UTC
