### ISSUE TITLE
Error in Building Popcorn Time for the Apple TV

### ISSUE THREAD

**Issue by mohorani** [PopcornTimeTV/PopcornTimeTV#27] opened 2016-03-25 00:33 UTC
"Linker command failed with exit code 1." Can you please fix this error. (This is an issue with PopcornKit). I get this error when actually building the app for the 4th Apple TV Gen but when building it for a simulator it works fine. Thanks.

**Comment by RefusedFlow** [comment] 2016-03-25 14:17
Duplicate of issue #28

**Closed** 2016-03-25 14:18 UTC
